[project]
name = "jukebox"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "soco==0.30.10",
]

[dependency-groups]
dev = [
    "pytest==7.4.4",
    "ruff==0.9.9",
]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"
extend-exclude = ["pn532/"]

[build-system]
# uv does not provide a build backend yet
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["jukebox", "pn532"]

[tool.hatch.build.targets.wheel]
include = ["jukebox", "pn532"]

[project.scripts]
jukebox = "jukebox.app:main"
player = "jukebox.players.utils:main"
reader = "jukebox.readers.utils:main"
