[tool.poetry]
name = "jukebox"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
soco = "^0.30.4"


[tool.poetry.group.dev.dependencies]
ruff = "^0.5.6"
pytest = "^8.3.2"

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"
extend-exclude = ["pn532/"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
