[project]
name = "jukebox"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "python-dotenv>=1.0.1",
    "soco>=0.30.5",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
    "ruff>=0.7.1",
]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"
extend-exclude = ["pn532/"]

[build-system]
# uv does not provide a build backend yet
requires = ["hatchling"]
build-backend = "hatchling.build"
