from typing import Protocol

from .entities import AppSettings, ResolvedAdminRuntimeConfig
from .types import JsonObject


class ReadOnlySettingsService(Protocol):
    def get_persisted_settings_view(self) -> JsonObject: ...

    def get_effective_settings_view(self) -> JsonObject: ...


class RuntimeSettingsService(Protocol):
    def get_effective_settings(self) -> AppSettings: ...

    def format_invalid_settings_error(self, error: str) -> str: ...


class SettingsService(ReadOnlySettingsService, RuntimeSettingsService, Protocol):
    def set_persisted_value(self, dotted_path: str, raw_value: str) -> JsonObject: ...

    def reset_persisted_value(self, dotted_path: str) -> JsonObject: ...

    def patch_persisted_settings(self, patch: JsonObject) -> JsonObject: ...

    def resolve_admin_runtime(self, verbose: bool = False) -> ResolvedAdminRuntimeConfig: ...
